#!/usr/bin/env bash
#This script tells a story taking data from /etc/passwd

while IFS=: read -r uname pwd uid gid gecos hdir sh
do
	echo "The user $uname is part of the $gid gang, lives in $hdir and rides $sh. $uid's place is protected by the passcode $pwd, more info about the user here: $gecos"
done
