#!/usr/bin/env bash
#This script writes 1-20 but with 3 exception

i=0
while ((i<20))
do
	((i++))
	echo $i
	case $i in
		4)
			echo "bad luck from China" ;;
		9)
			echo "bad luck from Japan" ;;
		17)
			echo "bad luck from Italy" ;;
		esac
	done
