#!/usr/bin/env bash
#This script displays data of a file

file="school"
if [ -e $file ]; then
	echo "school file exists"
	if [ -s $file ]; then
		echo "school file is empty"
		if [ -f $file ]; then
			echo "school is a regular file"
		fi
	else
		echo "school file is not empty"
	fi
	echo "school file does not exist"
fi
