#!/usr/bin/env bash
#it combines previous ones

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; kill $$' SIGTERM
trap 'rm /var/run/myscript.pid; kill $$)' SIGQUIT
pgrep $$ > "/var/run/myscript.pid"

while true
do
	echo "To infinity and beyond"
done

