#!/usr/bin/env bash
#This script prints "To infinity and beyond" until manual break with 2 seconds sleep
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
        echo "To infinity and beyond"
	sleep 2
done
